import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Michroma, Questrial } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const michroma = Michroma({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-michroma",
});

const questrial = Questrial({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-questrial",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${michroma.variable} ${questrial.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
